apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: training
nameSuffix: -stg
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: kite-app

images:
  - name: wanzinh/kite-app
    newTag: stg-3.3.3
