apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: training
nameSuffix: -stg
resources:
  - ../../base
patchesStrategicMerge:
  - replicas-patch.yaml

images:
  - name: wanzinh/kite-app
    newTag: stg-3.3.3
