apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: training
nameSuffix: -dev
resources:
  - ../../base
patchesStrategicMerge:
  - replicas-patch.yaml

images:
  - name: wanzinh/kite-app
    newTag: dev-4.4.4
