# --- Tài khoản ---
rootUser: "minioadmin"
rootPassword: "ChangeMe-Strong!"

# --- Lưu trữ ---
persistence:
  enabled: true
  size: 20Gi
  storageClass: nfs-client

# --- Service API ---
service:
  type: ClusterIP
  port: 9000

# --- Console ---
consoleService:
  type: NodePort
  port: 9001
  nodePort: 30901

# --- Metrics + ServiceMonitor ---
metrics:
  enabled: true            
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: kps
    includeNode: true           # scrape /minio/v2/metrics/node
    includeCluster: true        # scrape /minio/v2/metrics/cluster
    interval: 30s
    scrapeTimeout: 10s
