apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: training
nameSuffix: -prod
resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: kite-app
  - path: service-nodeport-patch.yaml
    target:
      kind: Service
      name: kite-app

images:
  - name: wanzinh/kite-app
    newTag: prod-3.3.3
